### ISSUE TITLE
issue related to import of sub functions within sorad qc  script

### ISSUE THREAD

**Issue by tjor** [monocle-h2020/MONDA#7]
When importing the qc monda script using:

from monda.sorad import qc  

the sub-functions are not recognised as attributes. e.g. if the function 'qc_lt_ed_filter' is called, then there is an error of the form:

module 'monda.sorad.qc' has no attribute 'qc_lt_ed_filter'

Similar errors do not occur for sorad `access' or `plots' scripts, where the sub functions are recognised. 

I do not know how to fix this, so I used a local import as a temporary work-around:
sys.path.append('/users/rsg/tjor/Sorad_mondademos/MONDA/src/monda/sorad')  
import qc 
import plots
import access

We also had this error when importing the qc module on adias.

**Comment by StefanSimis** [comment]
Your installed package may have a 'qc' folder in it which is being offered when you import qc, instead of the qc.py script which also sits in monda/sorad.  This would be likely on a local install which still has an old version (?) but not in a fresh environment, so perhaps the package on pypi is poorly configured. I will look into that.

**Comment by StefanSimis** [comment]
This is just to confirm that the wheel file on PyPI has the wrong folder structure. The tar.gz file seems correct. Not sure how that could happen, but I'll update PyPI ASAP

**Comment by StefanSimis** [comment]
this was fixed in version 0.2.1. closing.
